'use client';
import CollectionPageLayout from '@/components/CollectionPageLayout';

const products = [
  {
    id: 'bt1',
    name: 'Popees Chest-Printed Full Sleeve Top (0–9 Months) with Shoulder Opening for Baby Girls',
    shortName: 'Chest-Printed Full Sleeve Top',
    price: 'Rs. 235.00',
    originalPrice: 'Rs. 469.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/005a-jb-g-to-125',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529.jpg?v=1774117877&width=800',
    rating: '5.0',
    soldOut: true,
  },
  {
    id: 'bt2',
    name: 'Popees Half Sleeve Trendy Top (3-36 Months) for Girls',
    shortName: 'Half Sleeve Trendy Top',
    price: 'Rs. 199.50',
    originalPrice: 'Rs. 399.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/chic-trendy-cotton-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_1.jpg?v=1774117877&width=800',
    rating: '5.0',
    soldOut: true,
  },
  {
    id: 'bt3',
    name: 'Popees Half Sleeve Shoulder Open (3–36 Months) Chest Printed Top for Baby Girls',
    shortName: 'Shoulder Open Chest Printed Top',
    price: 'Rs. 175.00',
    originalPrice: 'Rs. 349.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/trendy-cotton-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_2.jpg?v=1774117877&width=800',
    rating: '5.0',
    soldOut: true,
  },
  {
    id: 'bt4',
    name: 'Popees Striped Short Sleeve (0–9 Months) Cute Bird Printed Top for Baby Girls',
    shortName: 'Striped Bird Printed Top',
    price: 'Rs. 105.00',
    originalPrice: 'Rs. 349.00',
    discount: '70% OFF',
    href: 'https://www.popees.com/products/trendy-comfy-printed-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'bt5',
    name: 'Popees Short Sleeve Top (3–36 Months) for Girls',
    shortName: 'Short Sleeve Top',
    price: 'Rs. 149.50',
    originalPrice: 'Rs. 299.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/adorable-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_1.jpg?v=1784619301&width=800',
    soldOut: true,
  },
  {
    id: 'bt6',
    name: 'Popees Half-Sleeved Embroidered Top (3–36 Months) Cute & Adorable Style for Girls',
    shortName: 'Half-Sleeved Embroidered Top',
    price: 'Rs. 250.00',
    originalPrice: 'Rs. 499.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/chic-adorable-half-sleeved-embroidered-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_2.jpg?v=1784619301&width=800',
    soldOut: true,
  },
  {
    id: 'bt7',
    name: 'Popees Printed Short Sleeve (3–36 Months) Soft & Stretchy Top for Baby Girls',
    shortName: 'Printed Short Sleeve Stretchy Top',
    price: 'Rs. 200.00',
    originalPrice: 'Rs. 399.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/stylish-and-comfortable-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'bt8',
    name: 'Popees Short Sleeve (3–36 Months) Chest Printed Top for Newborn Girls',
    shortName: 'Chest Printed Top for Newborns',
    price: 'Rs. 250.00',
    originalPrice: 'Rs. 499.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/popees-short-sleeve-0-9-months-chest-printed-top-for-newborn-girl',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898_3_a85f2339-55f0-471b-b92c-b33f2ce025bc.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'bt9',
    name: 'Popees Baby Girls Sleeveless Cotton Top | White | Newborn to 9 Months',
    shortName: 'Sleeveless Cotton Top — White',
    price: 'Rs. 849.00',
    href: 'https://www.popees.com/products/popees-baby-girls-sleeveless-cotton-top-white-newborn-to-9-months',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898_2.jpg?v=1774117939&width=800',
    soldOut: true,
  },
  {
    id: 'bt10',
    name: 'Popees Half Sleeve Chest Printed Top (3–36 Months) for Girls',
    shortName: 'Half Sleeve Chest Printed Top',
    price: 'Rs. 84.00',
    originalPrice: 'Rs. 279.00',
    discount: '70% OFF',
    href: 'https://www.popees.com/products/skin-friendly-comfy-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898_1.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'bt11',
    name: 'Popees Baby Girls Leopard Print Sleeveless Peplum Top | 3 Months–36 Months',
    shortName: 'Leopard Print Sleeveless Peplum Top',
    price: 'Rs. 599.00',
    href: 'https://www.popees.com/products/popees-baby-girls-leopard-sleeveless-top-3m-36m',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_5.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'bt12',
    name: 'Popees Floral Embroidered Denim Top (3–36 Months) for Girls',
    shortName: 'Floral Embroidered Denim Top',
    price: 'Rs. 350.00',
    originalPrice: 'Rs. 699.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/popees-short-sleeve-top-3-36-months-for-girls-copy-3',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_4.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'bt13',
    name: 'Popees Soft & Stylish All-Over Floral Printed Top (3–24 Months) for Baby Girls',
    shortName: 'All-Over Floral Printed Top',
    price: 'Rs. 399.00',
    href: 'https://www.popees.com/products/popees-half-sleeve-shoulder-open-3-36-months-chest-printed-top-for-baby-girls-copy',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'bt14',
    name: 'Popees Cotton Floral Print Top – Soft & Breathable, Half Sleeves (0–9 Months) for Baby Girls',
    shortName: 'Cotton Floral Print Half Sleeve Top',
    price: 'Rs. 399.00',
    href: 'https://www.popees.com/products/popees-cap-sleeve-back-open-top-0-9-months-for-baby-girls-copy-1',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_1.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'bt15',
    name: 'Popees Baby Girls Short Puff Sleeves Cotton Top | Blue | 3-36 Months',
    shortName: 'Short Puff Sleeves Cotton Top — Blue',
    price: 'Rs. 449.00',
    href: 'https://www.popees.com/products/popees-baby-girls-short-puff-sleeves-cotton-top-blue-3-36-months',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_2.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'bt16',
    name: 'Popees Short Sleeve Heart Print Top (0-9 Months) for Baby Girls',
    shortName: 'Heart Print Short Sleeve Top',
    price: 'Rs. 349.00',
    href: 'https://www.popees.com/products/everyday-chic-t-shirt-for-girls-copy',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'bt17',
    name: 'Popees Baby Girls Embroidered Cotton Top | White | 3-36 Months',
    shortName: 'Embroidered Cotton Top — White',
    price: 'Rs. 849.00',
    href: 'https://www.popees.com/products/popees-baby-girls-embroidered-cotton-top-white-3-36-months',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_1.jpg?v=1784619301&width=800',
    soldOut: true,
  },
  {
    id: 'bt18',
    name: 'Popees Baby Girls T-Shirt with Floral Patch | Rust Red | 9 Months to 4 Years',
    shortName: 'Floral Patch T-Shirt — Rust Red',
    price: 'Rs. 399.00',
    href: 'https://www.popees.com/products/popees-baby-girls-t-shirt-with-floral-patch-rust-red-9-months-to-4-years',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_2.jpg?v=1784619301&width=800',
    soldOut: true,
  },
  {
    id: 'bt19',
    name: 'Popees Heart-Printed Half Sleeve Front Open Top for Baby Girls (0–9 Months)',
    shortName: 'Heart-Printed Front Open Top',
    price: 'Rs. 399.00',
    href: 'https://www.popees.com/products/popees-half-sleeve-front-open-top-0-9-months-for-baby-girls-copy',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'bt20',
    name: 'Popees Baby Girls Flower Print Short Sleeve Cotton Top | Pink | 3 to 36 Months',
    shortName: 'Flower Print Cotton Top — Pink',
    price: 'Rs. 499.00',
    href: 'https://www.popees.com/products/popees-baby-girls-short-sleeve-cotton-top-pink-3-to-36-months',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898_1.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'bt21',
    name: 'Popees Summer Ready Short Sleeve Striped Rib Knit Top (3–36 Months) for Baby Girls',
    shortName: 'Striped Rib Knit Top',
    price: 'Rs. 449.00',
    href: 'https://www.popees.com/products/popees-short-sleeve-0-9-months-chest-printed-top-for-newborn-girls-copy',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898_2.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'bt22',
    name: 'Popees Printed Half Sleeve Front Open Top (0-9 Months) for Baby Girls',
    shortName: 'Printed Front Open Top',
    price: 'Rs. 399.00',
    href: 'https://www.popees.com/products/popees-cap-sleeve-back-open-top-0-9-months-for-baby-girls-copy',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'bt23',
    name: 'Popees Soft & Elegant White Ruffle Top (3–36 Months) for Baby Girls',
    shortName: 'Elegant White Ruffle Top',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-short-sleeve-top-3-36-months-for-girls-copy',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_2.jpg?v=1774117877&width=800',
    soldOut: true,
  },
];

export default function BabyTopNewPage() {
  return (
    <CollectionPageLayout
      title="Baby Tops"
      description="Soft, breathable cotton tops for newborns, infants and toddlers — designed for comfort, play and every little milestone."
      itemCount={products.length}
      products={products}
      highestPrice="849"
      showTitleHeading
      filterGroups={[
        { label: 'Availability' },
        { label: 'Price Range' },
        {
          label: 'Sleeve Type',
          options: ['Full Sleeve', 'Half Sleeve', 'Short Sleeve', 'Sleeveless'],
        },
        {
          label: 'Age Group',
          options: ['0–3 Months', '3–9 Months', '9–24 Months', '2–4 Years'],
        },
        {
          label: 'Style',
          options: ['Printed', 'Embroidered', 'Solid', 'Striped'],
        },
      ]}
    />
  );
}
