'use client';
import CollectionPageLayout from '@/components/CollectionPageLayout';

const products = [
  {
    id: 'gtp1',
    name: 'Popees Sleeveless Top with Collar for Girls (1–6 Years) – Fashionable & Comfy Wear',
    shortName: 'Sleeveless Collar Top',
    price: 'Rs. 250.00',
    originalPrice: 'Rs. 499.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/trendy-comfy-top-for-girls-1',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_1.jpg?v=1784619301&width=800',
    soldOut: true,
  },
  {
    id: 'gtp2',
    name: 'Popees Short Sleeve Back Half Open (1–8 Years) Printed Top for Baby Girls',
    shortName: 'Back Half Open Printed Top',
    price: 'Rs. 90.00',
    originalPrice: 'Rs. 299.00',
    discount: '70% OFF',
    href: 'https://www.popees.com/products/trendy-comfy-top-for-girls-2',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_2.jpg?v=1784619301&width=800',
    soldOut: true,
  },
  {
    id: 'gtp3',
    name: 'Popees Half Sleeve Front Printed (1–8 Years) Fashionable Cropped Top for Girls',
    shortName: 'Front Printed Cropped Top',
    price: 'Rs. 105.00',
    originalPrice: 'Rs. 349.00',
    discount: '70% OFF',
    href: 'https://www.popees.com/products/fashionable-cropped-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'gtp4',
    name: 'Popees Short Sleeve Front Printed (1–8 Years) Soft and Comfortable Top for Girls',
    shortName: 'Front Printed Comfortable Top',
    price: 'Rs. 120.00',
    originalPrice: 'Rs. 399.00',
    discount: '70% OFF',
    href: 'https://www.popees.com/products/fashionable-front-printed-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_1.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'gtp5',
    name: 'Popees Sleeveless Camisole (1–8 Years) for Girls',
    shortName: 'Sleeveless Camisole',
    price: 'Rs. 165.00',
    originalPrice: 'Rs. 549.00',
    discount: '70% OFF',
    href: 'https://www.popees.com/products/popees-sleeveless-vest-1-8-years-for-boys-pack-of-3-copy-1',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_2.jpg?v=1774117877&width=800',
    rating: '5.0',
    soldOut: true,
  },
  {
    id: 'gtp6',
    name: 'Popees Front-Open Collared Top (1–6 Years) – Lightweight & Comfortable Baby Girl Wear',
    shortName: 'Front-Open Collared Top',
    price: 'Rs. 350.00',
    originalPrice: 'Rs. 699.00',
    discount: '50% OFF',
    href: 'https://www.popees.com/products/stylish-top-for-girls',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'gtp7',
    name: 'Popees Baby Girls T-Shirt with Floral Patch | Rust Red | 9 Months to 4 Years',
    shortName: 'Floral Patch T-Shirt — Rust Red',
    price: 'Rs. 399.00',
    href: 'https://www.popees.com/products/popees-baby-girls-t-shirt-with-floral-patch-rust-red-9-months-to-4-years',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_4.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'gtp8',
    name: 'Popees Baby Girls Short Sleeves Cotton Top | Red | 9 Months To 4 Years',
    shortName: 'Short Sleeve Cotton Top — Red',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-baby-girls-short-sleeves-cotton-top-red-months-to-4-years',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_5.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'gtp9',
    name: 'Popees Baby Sleeveless High Neck Cotton Top | Soft Baby Winter Wear | 9M–4 Years',
    shortName: 'Sleeveless High Neck Cotton Top',
    price: 'Rs. 649.00',
    href: 'https://www.popees.com/products/popees-baby-sleeveless-high-neck-cotton-top-soft-comfortable-baby-winter-wear-9-m-4-years',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'gtp10',
    name: 'Popees Baby Girls Floral Print Ribbed Half Sleeve Collared Top | 9M–4Y',
    shortName: 'Floral Ribbed Collared Top',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-baby-girls-floral-print-ribbed-half-sleeve-collared-top-9m-4y',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898_1.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'gtp11',
    name: 'Popees Baby Girls Floral Cotton Top | Cream Long Sleeve Peter Pan Collar (9M–4Y)',
    shortName: 'Floral Peter Pan Collar Top — Cream',
    price: 'Rs. 699.00',
    href: 'https://www.popees.com/products/popees-baby-girls-cream-floral-cotton-full-sleeve-peter-pan-collar-top-9-months-4-years',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-B-JH-898_2.jpg?v=1774117938&width=800',
    soldOut: true,
  },
  {
    id: 'gtp12',
    name: 'Popees Soft & Stylish Heart Printed Full Sleeve Top (1-9 Months) for Newborn Girls',
    shortName: 'Heart Printed Full Sleeve Top',
    price: 'Rs. 799.00',
    href: 'https://www.popees.com/products/popees-front-open-1-9-months-cute-and-comfortable-top-for-new-born-girls-copy-1',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'gtp13',
    name: 'Popees Baby Girls Polka Dot Ribbed Half Sleeve Collared Top | 9M–4Y',
    shortName: 'Polka Dot Ribbed Collared Top',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-baby-girls-polka-dot-ribbed-half-sleeve-collared-top-9m-4y',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_1.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'gtp14',
    name: 'Popees Baby Girls Cotton Floral Printed Puff Sleeve Top | Soft Breathable Casual Wear (1–6 Years)',
    shortName: 'Floral Puff Sleeve Top',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-baby-girls-cotton-floral-printed-puff-sleeve-top-1-6y',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_2.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'gtp15',
    name: 'Popees Baby Girls Cotton Embroidered Top | 9 Months to 4 Years',
    shortName: 'Cotton Embroidered Top',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-baby-girls-cotton-embroidered-top-9-months-to-4-years',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'gtp16',
    name: 'Popees Baby Girls Soft Ribbed Cotton Top with Floral Eyelet Lace Ruffle Detail | Sleeveless | 9M–4 Years',
    shortName: 'Ribbed Lace Ruffle Sleeveless Top',
    price: 'Rs. 649.00',
    href: 'https://www.popees.com/products/popees-baby-girls-soft-ribbed-cotton-top-with-floral-eyelet-lace-ruffle-detail-sleeveless-top-9-m-4-years',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_1.jpg?v=1784619301&width=800',
    soldOut: true,
  },
  {
    id: 'gtp17',
    name: 'Popees Baby Girls Cotton Flutter Sleeve Embroidered Top | Cream | 3 Months–4 Years',
    shortName: 'Flutter Sleeve Embroidered Top — Cream',
    price: 'Rs. 699.00',
    href: 'https://www.popees.com/products/popees-baby-girls-cotton-flutter-sleeve-embroidered-top-soft-floral-embroidery-casual-top-cream-3-month-4-years',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_2.jpg?v=1784619301&width=800',
    soldOut: true,
  },
  {
    id: 'gtp18',
    name: 'Popees Baby Girls Cotton Polo Top | White Embroidered Collar Half Sleeve (9 Months–4 Years)',
    shortName: 'Cotton Polo Top — White Collar',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-baby-girls-ribbed-cotton-collared-top-cameo-brown-9-months-4-years-copy',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_4.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'gtp19',
    name: 'Popees Baby Girls Ribbed Cotton Collared Top | Cameo Brown | 9 Months–4 Years',
    shortName: 'Ribbed Cotton Collared Top — Cameo Brown',
    price: 'Rs. 649.00',
    href: 'https://www.popees.com/products/popees-baby-girls-ribbed-cotton-collared-top-peach-pink',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'gtp20',
    name: 'Popees Baby Girls Knit Short Sleeve Top | 9 Months to 4 Years',
    shortName: 'Knit Short Sleeve Top',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-baby-girls-knit-short-sleeve-top-9-months-to-4-years',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_1.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'gtp21',
    name: 'Popees Girls Floral Print Cotton Puff Sleeve Top for Kids (1–6 Years)',
    shortName: 'Floral Puff Sleeve Top for Kids',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-girls-floral-cotton-puff-sleeve-top-1-6-years',
    img: 'https://www.popees.com/cdn/shop/files/007A-JB-G-DR-529_2.jpg?v=1774117877&width=800',
    soldOut: true,
  },
  {
    id: 'gtp22',
    name: 'Popees Girls Cotton Floral Printed Puff Sleeve Top | Round Neck Daily Wear | 1–6 Years',
    shortName: 'Cotton Floral Puff Sleeve Daily Top',
    price: 'Rs. 549.00',
    href: 'https://www.popees.com/products/popees-girls-cotton-floral-puff-sleeve-top-kids-1-6-years',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F.jpg?v=1784619302&width=800',
    soldOut: true,
  },
  {
    id: 'gtp23',
    name: 'Popees Baby Girls Cotton Textured Tie-Up Top with Collar, Soft Breathable (1–6 Years)',
    shortName: 'Textured Tie-Up Collar Top',
    price: 'Rs. 849.00',
    href: 'https://www.popees.com/products/popees-baby-girls-cotton-textured-tie-up-collar-top-1-6y',
    img: 'https://www.popees.com/cdn/shop/files/009A-KF-G-TB-957F_2.jpg?v=1784619301&width=800',
    soldOut: true,
  },
];

export default function GirlsTopNewPage() {
  return (
    <CollectionPageLayout
      title="Girls Tops"
      description="Stylish and comfortable tops for baby girls and kids — from floral puff sleeves and collared tops to camisoles and embroidered styles."
      itemCount={products.length}
      products={products}
      highestPrice="849"
      showTitleHeading
      filterGroups={[
        { label: 'Availability' },
        { label: 'Price Range' },
        { label: 'Sleeve Type', options: ['Full Sleeve', 'Half Sleeve', 'Short Sleeve', 'Sleeveless', 'Flutter Sleeve', 'Puff Sleeve'] },
        { label: 'Age Group', options: ['0–9 Months', '9M–4 Years', '1–6 Years', '1–8 Years'] },
        { label: 'Style', options: ['Printed', 'Embroidered', 'Plain', 'Floral', 'Collared'] },
      ]}
    />
  );
}
